:: code --list-extensions
code --install-extension cschlosser.doxdocgen --force
code --install-extension jeff-hykin.better-cpp-syntax --force
code --install-extension ms-vscode-remote.remote-containers --force
code --install-extension ms-vscode-remote.remote-ssh --force
code --install-extension ms-vscode-remote.remote-wsl --force
code --install-extension ms-vscode.cmake-tools --force
code --install-extension ms-vscode.cpptools --force
code --install-extension ms-vscode.cpptools-extension-pack --force
code --install-extension ms-vscode.cpptools-themes --force
code --install-extension ms-vscode.powershell --force
code --install-extension ms-vscode.sublime-keybindings --force
code --install-extension Oracle.oracledevtools --force
code --install-extension redhat.java --force
code --install-extension twxs.cmake --force
code --install-extension VisualStudioExptTeam.vscodeintellicode --force
code --install-extension vscjava.vscode-java-debug --force
code --install-extension vscjava.vscode-java-dependency --force
code --install-extension vscjava.vscode-java-pack --force
code --install-extension vscjava.vscode-java-test --force
code --install-extension vscjava.vscode-maven --force
code --install-extension xyz.plsql-language --force
code --install-extension yo1dog.cursor-align --force
